mozilla-b2g/firefoxos-loop-client

- app/js/helpers/room/room_controller.js
- app/js/helpers/telemetry.js
- app/js/screens/room/join_room.js
Reporting camera used in a room to Telemetry system.
> Bug 1107531 - Reporting camera used per room to Telemetry

- app/js/helpers/room/room_controller.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1121413 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1121413.
> Bug 1121413 - [Loop] Incorrect error message shown when trying to join a full room

- app/js/controller.js
- app/manifest.webapp
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1121370 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1121370.
> Bug 1121370 - [Loop] Notification persists after powering the device off/on but does not do anything

- app/call_screen/js/call_manager.js
- app/call_screen/js/call_screen_ui_minified.js
- app/index.html
- app/js/helpers/room/room_manager.js
- app/js/helpers/speaker_manager.js
- app/js/helpers/tone_player_helper.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1120905. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1120905-follow-up.
> Bug 1120905 - [Loop] When Loop is opened in foreground , the sound is heard from the speaker when it was disconnected (same happens with headset)

- app/js/config.js
- app/js/helpers/client_request_helper.js
- app/js/screens/room_detail.js
- app/js/utils.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1121924 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1121924.
> Bug 1121924 - [Loop] Expiration date is longer than 56 days when the date of the device is change to the past

- app/js/helpers/activities.js
- app/js/helpers/telemetry.js
number of received rooms. The count is incremented everytime a new room is added to calllog. The count is just an increment over a numeric variable in Telemetry.
> Bug 1113598 - Telemetry report: Number of received rooms

- app/js/helpers/rooms_db.js
- app/js/helpers/telemetry.js
- app/js/screens/create_room.js
Number of times a room is renamed;
> Bug 1121449 - [Loop] [Telemetry] Renaming rooms

- app/js/helpers/room/room_controller.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1124707 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1124707.
> Bug 1124707 - Adding sound when leaving a Room from Firefox Hello application for every user that leaves a Room

- app/elements/shared_with.html
- app/js/screens/shared_with.js
...tact is removed from the Agenda
> Bug 1120135 - Invitees list in Room details is not correctly updated if an invitee contact is removed from the Agenda r=borjasalguero

- app/js/helpers/room/room_controller.js
- app/js/helpers/rooms_db.js
- app/js/helpers/telemetry.js
number of times a room is visited and used depending on rooms with or without subject
> Bug 1121476 - [Loop][Telemetry] Reporting:# times a room is visited&used

- app/js/helpers/room/room_controller.js
- app/js/helpers/room/room_manager.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1124761 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1124761.
> Bug 1124761 - When a user is connected to a Room and receive or make an GSM call, his video stream is frozen

- app/js/helpers/room/room_controller.js
See bug  https://bugzilla.mozilla.org/show_bug.cgi?id=1126337 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1126337.
> Bug 1126337 - [Loop] Play ended tone when leaving a Room from Firefox Hello application for every user that leaves a Room

- .travis.yml
- README.md
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1126861 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/travis-support.
> Bug 1126861 - [Loop] Add Travis CI support FxOS Hello unit testing

- app/js/controller.js
- app/js/helpers/call_screen_manager.js
- app/js/helpers/room/room_controller.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1126860 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1126860.
> Bug 1126860 - [Loop] Wrong status in a room conversation when receives a loop call

- app/js/controller.js
- app/js/helpers/call_screen_manager.js
- app/js/helpers/room/room_controller.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1127320. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1127320.
> Bug 1127320 - [Loop] The user should not be able to join a room when a loop call is active

- app/js/helpers/room/room_controller.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1127791 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1127791.
>  Bug 1127791 - [Loop] "You are the only one in the room" message disappear in Device B when User A receives a GSM call and tries to join to the room

- app/js/helpers/tone_player_helper.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1126234 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1126234.
> Bug 1126234 - [Loop] Sound is heard through the speaker when opening loop app 

- app/js/helpers/room/room_controller.js
- app/js/helpers/room/room_manager.js
- app/js/screens/room/room_ui.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1128697 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1128697.
> Bug 1128697 - [Loop] Mute button changes meaning (mute vs unmuted) when exiting a room with mute on

- app/js/helpers/account_helper.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1129842 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1129842.
> Bug 1129842 - [Loop] Warning message is shown when user tries to logged in phone number and closes the screen

- app/js/helpers/account_helper.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1129885 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1129885.
> Bug 1129885 - [Loop] User (logged with MobileID) is logged out of the Loop application

- app/js/helpers/call_progress_helper.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1126860 please. Action happens athttps://github.com/jaoo/firefoxos-loop-client/tree/1126860-follow-up.
> Bug 1129979 - [Loop] Follow up bug 1126860 user being rejected does not handle correctly the reject reason

- app/js/controller.js
- app/js/helpers/activities.js
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1131607 please. Action happens at https://github.com/jaoo/firefoxos-loop-client/tree/1131607.
> Bug 1131607 - [Loop] It's possible join in a room via Standalone UI, when another communication is established in other room, from the same device

- Gruntfile.js
- package.json
- tasks/firefoxos.js
So that Grunt continues working with FxOS master
> Change Grunt Dependencies, r=borjasalguero
